### ISSUE TITLE
Meta-issue:  countdown to 1.0

### ISSUE THREAD

**Issue by dwinter** [ropensci/rentrez#32]
List of all issues that need to be resolved prior to a (more) stable 1.0 release:

* [x] #31 import rather than depend on XML
* [x] #30 Moar tests
* [x] #28 Moar vignette
* [x] #27 Better print functions for some APIs returned objects
* [x] #26 Match use of `httr` to the package's best practices
* [x] #37  Represent the "translation" of a search query
* [x] #33 Include entrez_post examples in documentation
    
(And I guess this issue... but adding that to this set must be some version Russel's Paradox...)

Almost there now. Real final steps

* [x] Close edit for spelling grammar and syntax in 
  * [x] Docs
  * [x] Readme
* [x] Test against fulltext
* [x] Update NEWS file
* [x] Write blog post announcing changes since last version
* [x] Submit to CRAN
